baseurl = "https://365clock.com"
title = "Calendar Clock"
# theme = "hugo-coder"
languagecode = "en"
defaultcontentlanguage = "en"

paginate = 20
canonifyurls = true

pygmentsstyle = "bw"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

disqusShortname = "yourdiscussshortname"

[params]
    author = "Olivia Jacobs"
    info = "A visual clock to keep track of the year"
    description = "A visual clock to keep track of the year"
    keywords = "project,personal"

    footercontent = "Oh yes, it's very beatiful! More to come..."

    hidecredits = false
    hidecopyright = false

    rtl = false

    math = true

# Menu links
[[menu.main]]
    name = "About"
    weight = 2
    url = "/about/"
